-- DEPRECATED — use supabase/setup.sql instead
--
-- fix-signup.sql previously duplicated the signup trigger and seed orgs from setup.sql.
-- Before launch, run the full canonical script:
--
--   supabase/setup.sql
--
-- That file includes gcc_handle_new_user(), the auth.users trigger, default org seeds,
-- and all table/RLS definitions. Running setup.sql on an existing project is safe
-- (CREATE IF NOT EXISTS / ON CONFLICT DO NOTHING).
